CREATE TABLE IF NOT EXISTS product(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description VARCHAR(100)NOT NULL,
price NUMERIC NOT NULL,
weight DOUBLE NOT NULL,
category INT NOT NULL,
supplier INT NOT NULL,
PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS product_category(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description VARCHAR(100)NOT NULL,
PRIMARY KEY(id));
