create sequence authority_sequence start with 1 increment by 1;

create table authority (id integer GENERATED BY DEFAULT AS IDENTITY, user_type varchar(10), primary key (id));
create table shop_user (username varchar(255), pwd varchar(255), enabled boolean, primary key (username));
create table user_authority (user_id varchar(255), authority_id integer, primary key (user_id, authority_id));
alter table user_authority add constraint FKtfp2hwv6siwe2rkt9nq8cqvst foreign key (user_id) references shop_user;
alter table user_authority add constraint FKtfp3hwv6siwe2rkt9nq8cqvst foreign key (authority_id) references authority;

insert into shop_user (username, pwd, enabled) values ('user', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.', true);
insert into shop_user (username, pwd, enabled) values ('user2', '$2a$10$trT3.R/Nfey62eczbKEnueTcIbJXW.u1ffAo/XfyLpofwNDbEB86O', false);
insert into authority (user_type) values ('CUSTOMER');
insert into user_authority (user_id, authority_id) values ('user', 1);
insert into user_authority (user_id, authority_id) values ('user2', 1);
