create sequence revenue_sequence start with 1 increment by 1;
create table revenue (id integer GENERATED BY DEFAULT AS IDENTITY, date DATE, location integer, sum DECIMAL, primary key (id));

alter table product_order add created_on TIMESTAMP;
alter table revenue add constraint FK6t3m0kaf6fubuus338gf7xmn8 foreign key (location) references location;
